# -*- coding: utf-8 -*-
"""iris_app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hz2ivi1aRn1Sax0aQLqPpbZHbBpFhDz6
"""

import streamlit as st
import numpy as np
import joblib

st.markdown('## Iris species prediction')
sepal_length = st.number_input('sepal length (cm)')
sepal_width = st.number_input('sepal width(cm)')
petal_length=st.number-input('prtal length (cm)')
petal_width=st.number_input('petal width (cm)')

if st.button('predict'):
    model = joblib.load('iris_model.pkl')
    x=np.array([sepal_length,sepal_width,petal_length,petal_width])
    if any(x<=0):
      st.markdown('### Inputs must be greater than 0')
    else:
      st.markdown(f'###prediction is '{model.predict([[sepal_length,sepal_width,petal_length,petal_width]])[0]}')
